# Generated by Django 2.2.7 on 2019-11-19 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.IntegerField()),
                ('item_code', models.IntegerField()),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('unit_price', models.FloatField()),
                ('country', models.CharField(max_length=100)),
                ('cashier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
