# Generated by Django 2.2.7 on 2019-11-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='item_code',
            field=models.CharField(max_length=100),
        ),
    ]
